import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  deploySidebar: [
    {
      type: 'category',
      label: 'Deploy',
      collapsible: false,
      items: [
        'intro/self-hosting',
        'intro/local-setup',
      ],
    },
  ],

  adminSidebar: [
    {
      type: 'category',
      label: 'Admin Guide',
      collapsible: false,
      items: [
        'admin-guide/admin-overview',
        'admin-guide/admin-application-context',
        'admin-guide/admin-guardrails-api',
        'admin-guide/admin-guardrails',
      ],
    },
  ],

  introSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: false,
      items: [
        'intro/overview',
        'intro/core-concepts',
        'intro/why-not-rules',
        'intro/quickstart',
        'intro/builder-workflow',
        'intro/application-context',
        'intro/guardrails',
        'intro/patterns',
        'intro/common-mistakes',
        'intro/snippets',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsible: false,
      items: [
        'api-reference/overview',
        'api-reference/end-to-end-workflow',
        'api-reference/errors',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        'api-reference/context',
        'api-reference/guardrails',
        'api-reference/tasks',
        'api-reference/execution',
        'api-reference/conditions',
        'api-reference/decisions',
        'api-reference/feedback',
      ],
    },
    {
      type: 'category',
      label: 'Interactive Reference',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'App Developer API',
        description: 'Interactive reference — try every endpoint directly from your browser.',
        slug: '/api-reference/interactive',
      },
      items: [{ type: 'autogenerated', dirName: 'api-reference/generated' }],
    },
  ],

  pythonSidebar: [
    {
      type: 'category',
      label: 'Python Backend SDK',
      collapsible: false,
      items: [
        'python-sdk/python-overview',
        'python-sdk/application-context',
        'python-sdk/guardrails',
        'python-sdk/concept-execution',
        'python-sdk/condition-evaluation',
        'python-sdk/compilation',
        'python-sdk/registry',
        'python-sdk/agents',
      ],
    },
  ],

  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Case Studies',
      collapsible: false,
      items: [
        'tutorials/deal-intelligence',
        'tutorials/xbrl-compliance',
        'tutorials/financial-risk-monitoring',
        'tutorials/healthcare-payor-provider',
        'tutorials/devops-observability',
        'tutorials/clinical-trials-fda',
      ],
    },
  ],

};

export default sidebars;
